# Ubuntu-ja translation of update-manager.
# Copyright (C) 2006 THE update-manager'S COPYRIGHT HOLDER
# This file is distributed under the same license as the update-manager package.
# Ikuya Awashiro <ikuya@fruitsbasket.info>, 2006.
# Hiroyuki Ikezoe <ikezoe@good-day.co.jp>, 2005
#
#
#: ../DistUpgrade/DistUpgradeController.py:1045
msgid ""
msgstr ""
"Project-Id-Version: update-manager 0.42.4\n"
"Report-Msgid-Bugs-To: sebastian.heinlein@web.de\n"
"POT-Creation-Date: 2021-07-05 10:53+0200\n"
"PO-Revision-Date: 2019-06-18 17:54+0000\n"
"Last-Translator: Mitsuya Shibata <mty.shibata@gmail.com>\n"
"Language-Team: Ubuntu Japanese Team <ubuntu-ja-users@freeml.com>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"X-Launchpad-Export-Date: 2019-11-15 04:47+0000\n"
"X-Generator: Launchpad (build c597c3229eb023b1e626162d5947141bf7befb13)\n"

#. TRANSLATORS: %s is a country
#: ../DistUpgrade/distro.py:215 ../DistUpgrade/distro.py:446
#, python-format
msgid "Server for %s"
msgstr "%s にあるサーバー"

#. More than one server is used. Since we don't handle this case
#. in the user interface we set "custom servers" to true and
#. append a list of all used servers
#: ../DistUpgrade/distro.py:233 ../DistUpgrade/distro.py:239
#: ../DistUpgrade/distro.py:255
msgid "Main server"
msgstr "メインサーバー"

#: ../DistUpgrade/distro.py:259
msgid "Custom servers"
msgstr "カスタムサーバー群"

#: ../DistUpgrade/DistUpgradeCache.py:182
msgid "Remove package in bad state"
msgid_plural "Remove packages in bad state"
msgstr[0] "壊れた状態のパッケージを削除する"

#: ../DistUpgrade/DistUpgradeCache.py:185
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Do you want to remove this package now "
"to continue?"
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archives can be found for them. Do you want to remove these packages "
"now to continue?"
msgstr[0] ""
"パッケージ '%s' は 矛盾した状態にあり再インストールが必要ですが、そのための"
"アーカイブを見つけることができません。 このパッケージを削除して先に進めます"
"か？"

#. FIXME: not ideal error message, but we just reuse a
#. existing one here to avoid a new string
#: ../DistUpgrade/DistUpgradeCache.py:301
msgid "The server may be overloaded"
msgstr "サーバーが過負荷状態にある可能性があります"

#: ../DistUpgrade/DistUpgradeCache.py:414
msgid "Broken packages"
msgstr "壊れたパッケージ"

#: ../DistUpgrade/DistUpgradeCache.py:415
msgid ""
"Your system contains broken packages that couldn't be fixed with this "
"software. Please fix them first using synaptic or apt-get before proceeding."
msgstr ""
"システムにはこのソフトウェアでは修復できない壊れたパッケージが含まれていま"
"す。 Synaptic や apt-get を使って最初に修正してください。"

#: ../DistUpgrade/DistUpgradeCache.py:660
#, fuzzy, python-format
msgid "Broken packages after upgrade: %s"
msgstr "壊れたパッケージ"

#. the most likely problem is the 3rd party pkgs so don't address
#. foreignPkgs and devRelease being True
#: ../DistUpgrade/DistUpgradeCache.py:669
msgid ""
"An unresolvable problem occurred while calculating the upgrade.\n"
"\n"
" "
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:672
msgid ""
"This was likely caused by:\n"
" * Unofficial software packages not provided by Ubuntu\n"
"Please use the tool 'ppa-purge' from the ppa-purge \n"
"package to remove software from a Launchpad PPA and \n"
"try the upgrade again.\n"
"\n"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:680
msgid ""
"This was caused by:\n"
" * Upgrading to a pre-release version of Ubuntu\n"
"This is most likely a transient problem, \n"
"please try again later.\n"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:687
msgid "This is most likely a transient problem, please try again later."
msgstr "これは一時的な問題のようです。後でもう一度試してください。"

#: ../DistUpgrade/DistUpgradeCache.py:690
msgid ""
"If none of this applies, then please report this bug using the command "
"'ubuntu-bug ubuntu-release-upgrader-core' in a terminal. "
msgstr ""
"上記のいずれにも当てはまらない場合は、端末でコマンド 'ubuntu-bug ubuntu-"
"release-upgrader-core'を使用してこのバグを報告してください。 "

#: ../DistUpgrade/DistUpgradeCache.py:692
msgid ""
"If you want to investigate this yourself the log files in '/var/log/dist-"
"upgrade' will contain details about the upgrade. Specifically, look at 'main."
"log' and 'apt.log'."
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:698
msgid "Could not calculate the upgrade"
msgstr "アップグレード作業を見積もれません"

#: ../DistUpgrade/DistUpgradeCache.py:757
msgid "Error authenticating some packages"
msgstr "パッケージの認証において、エラーがありました"

#: ../DistUpgrade/DistUpgradeCache.py:758
msgid ""
"It was not possible to authenticate some packages. This may be a transient "
"network problem. You may want to try again later. See below for a list of "
"unauthenticated packages."
msgstr ""
"いくつかのパッケージが認証できませんでした。これは一時的なネットワークの問題"
"かもしれません。あとで再び試してみてください。以下に認証できなかったパッケー"
"ジのリストが表示されます。"

#: ../DistUpgrade/DistUpgradeCache.py:779
#, python-format
msgid ""
"The package '%s' is marked for removal but it is in the removal blacklist."
msgstr ""
"パッケージ'%s'は「削除」と指定されていますが、削除ブラックリストに入っていま"
"す。"

#: ../DistUpgrade/DistUpgradeCache.py:785
#, python-format
msgid "The essential package '%s' is marked for removal."
msgstr "必須パッケージ'%s'に「削除」マークがついています。"

#: ../DistUpgrade/DistUpgradeCache.py:794
#, python-format
msgid "Trying to install blacklisted version '%s'"
msgstr ""
"ブラックリストに入っているバージョン '%s' をインストールしようとしています"

#: ../DistUpgrade/DistUpgradeCache.py:916
#, python-format
msgid "Can't install '%s'"
msgstr "'%s'をインストールすることができません。"

#: ../DistUpgrade/DistUpgradeCache.py:917
msgid ""
"It was impossible to install a required package. Please report this as a bug "
"using 'ubuntu-bug ubuntu-release-upgrader-core' in a terminal."
msgstr ""
"必要なパッケージをインストールできませんでした。端末上から 'ubuntu-bug "
"ubuntu-release-upgrader-core' を実行し、これをバグとして報告してください。"

#: ../DistUpgrade/DistUpgradeCache.py:928
msgid "Can't guess meta-package"
msgstr "メタパッケージを推測できません"

#: ../DistUpgrade/DistUpgradeCache.py:929
#, python-format
msgid ""
"Your system does not contain a %s or %s package and it was not possible to "
"detect which version of Ubuntu you are running.\n"
" Please install one of the packages above first using synaptic or apt-get "
"before proceeding."
msgstr ""
"お使いのシステムには %s ないし %s パッケージがなく、どのバージョンの Ubuntu "
"が実行中かを検知することができません。\n"
" 続行する前に synaptic または apt-get を使って上記のパッケージのうちの1つをま"
"ずインストールしてください。"

#: ../DistUpgrade/DistUpgradeController.py:112
msgid "Reading cache"
msgstr "キャッシュを読み込み中"

#: ../DistUpgrade/DistUpgradeController.py:219
msgid "Unable to get exclusive lock"
msgstr "排他的なロックができません"

#: ../DistUpgrade/DistUpgradeController.py:220
msgid ""
"This usually means that another package management application (like apt-get "
"or aptitude) already running. Please close that application first."
msgstr ""
"パッケージマネージャーは一度にひとつしか起動できません。apt-getやaptitudeなど"
"のような、他のパッケージマネージャーを終了してください。"

#: ../DistUpgrade/DistUpgradeController.py:278
msgid "Upgrading over remote connection not supported"
msgstr "リモート接続経由でのアップグレードはサポートされていません"

#: ../DistUpgrade/DistUpgradeController.py:279
msgid ""
"You are running the upgrade over a remote ssh connection with a frontend "
"that does not support this. Please try a text mode upgrade with 'do-release-"
"upgrade'.\n"
"\n"
"The upgrade will abort now. Please try without ssh."
msgstr ""
"このアップグレード処理は、リモートSSH経由で実行されたフロントエンドGUIから実"
"行されているようです。\n"
"このツールはそうした処理をサポートしていません。\n"
"\n"
"もしリモートからのアップグレードを望むなら、テキストモードでのアップグレード "
"'do-release-upgrade' を試してみてください。\n"
"\n"
"アップグレードは中断されます。SSHを経由しない起動方法で実行してください。"

#: ../DistUpgrade/DistUpgradeController.py:293
msgid "Continue running under SSH?"
msgstr "SSH経由で実行していますが、続けますか？"

#: ../DistUpgrade/DistUpgradeController.py:294
#, python-format
msgid ""
"This session appears to be running under ssh. It is not recommended to "
"perform a upgrade over ssh currently because in case of failure it is harder "
"to recover.\n"
"\n"
"If you continue, an additional ssh daemon will be started at port '%s'.\n"
"Do you want to continue?"
msgstr ""
"このセッションはSSH上で実行されているようです。アップグレードをSSH越しに行う"
"ことは推奨されません。アップグレードに失敗した時の復元が困難になるからで"
"す。\n"
"\n"
"続行する場合、追加のSSHデーモンをポート '%s' で起動します。\n"
"本当に作業を進めてよろしいですか？"

#: ../DistUpgrade/DistUpgradeController.py:308
msgid "Starting additional sshd"
msgstr "予備のsshdを開始します"

#: ../DistUpgrade/DistUpgradeController.py:309
#, python-format
msgid ""
"To make recovery in case of failure easier, an additional sshd will be "
"started on port '%s'. If anything goes wrong with the running ssh you can "
"still connect to the additional one.\n"
msgstr ""
"障害が起こったときに復旧しやすくするため、ポート '%s' でもう一つの sshd を開"
"始します。現在実行中のsshにおかしなことが起きても、もう一方のポートに接続する"
"ことができます。\n"

#: ../DistUpgrade/DistUpgradeController.py:317
#, python-format
msgid ""
"If you run a firewall, you may need to temporarily open this port. As this "
"is potentially dangerous it's not done automatically. You can open the port "
"with e.g.:\n"
"'%s'"
msgstr ""
"ファイアウォールを実行している場合、このポートを一時的に開く必要があります。"
"この操作は、潜在的な危険があるため自動的には行われません。以下の例のようにし"
"てポートを開けます:\n"
"'%s'"

#: ../DistUpgrade/DistUpgradeController.py:395
#: ../DistUpgrade/DistUpgradeController.py:419
msgid "Can not upgrade"
msgstr "アップグレードできません"

#: ../DistUpgrade/DistUpgradeController.py:396
#, python-format
msgid "An upgrade from '%s' to '%s' is not supported with this tool."
msgstr ""
"'%s' から '%s' へのアップグレードは、このツールではサポートされていません。"

#: ../DistUpgrade/DistUpgradeController.py:420
msgid ""
"Your python3 install is corrupted. Please fix the '/usr/bin/python3' symlink."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:449
#, python-format
msgid "Can not write to '%s'"
msgstr "'%s' に書き込みできません"

#: ../DistUpgrade/DistUpgradeController.py:450
#, python-format
msgid ""
"Its not possible to write to the system directory '%s' on your system. The "
"upgrade can not continue.\n"
"Please make sure that the system directory is writable."
msgstr ""
"システムディレクトリ '%s' に書き込みできないため、アップグレードを続行できま"
"せん。\n"
"システムディレクトリが書き込み可能かどうか確認してください。"

#: ../DistUpgrade/DistUpgradeController.py:617
#, python-format
msgid "Not for humans during development stage of release %s"
msgstr "開発段階のリリース %s であり人間向けではありません"

#: ../DistUpgrade/DistUpgradeController.py:717
#, python-format
msgid "disabled on upgrade to %s"
msgstr "%sへのアップグレード時に無効化されました"

#: ../DistUpgrade/DistUpgradeController.py:776
msgid "No valid sources.list entry found"
msgstr "有効なsources.listエントリーが見つかりません"

#: ../DistUpgrade/DistUpgradeController.py:777
#, python-format
msgid ""
"While scanning your repository information no entry about %s could be "
"found.\n"
"\n"
"An upgrade might not succeed.\n"
"\n"
"Do you want to continue anyway?"
msgstr ""
"レポジトリ情報をスキャンしましたが、%sに関するエントリーが見つかりませんでし"
"た。\n"
"\n"
"アップグレードに成功しないかもしれません。\n"
"\n"
"それでも続けますか?"

#: ../DistUpgrade/DistUpgradeController.py:787
msgid "No valid mirror found"
msgstr "利用可能なミラーが見つかりません"

#: ../DistUpgrade/DistUpgradeController.py:788
#, python-format
msgid ""
"While scanning your repository information no mirror entry for the upgrade "
"was found. This can happen if you run an internal mirror or if the mirror "
"information is out of date.\n"
"\n"
"Do you want to rewrite your 'sources.list' file anyway? If you choose 'Yes' "
"here it will update all '%s' to '%s' entries.\n"
"If you select 'No' the upgrade will cancel."
msgstr ""
"リポジトリ情報を検査しましたが、アップグレード用のミラーエントリーが見つかり"
"ませんでした。内部ミラーを動かしているか、ミラー情報が古くなっている可能性が"
"あります。\n"
"\n"
"'sources.list'ファイルを書き換えますか?「はい」を選ぶと、'sources."
"list'の'%s'エントリーをすべて'%s'に変更します。\n"
"「いいえ」を選ぶと、アップグレードを中止します。"

#. hm, still nothing useful ...
#: ../DistUpgrade/DistUpgradeController.py:808
msgid "Generate default sources?"
msgstr "標準のリポジトリ設定ファイルを生成しますか？"

#: ../DistUpgrade/DistUpgradeController.py:809
#, python-format
msgid ""
"After scanning your 'sources.list' no valid entry for '%s' was found.\n"
"\n"
"Should default entries for '%s' be added? If you select 'No', the upgrade "
"will cancel."
msgstr ""
"システムの 'sources.list' を確認しましたが、有効な '%s' のためのエントリが見"
"つかりません。\n"
"\n"
"'%s' のためのデフォルト設定エントリを追加しますか？　「いいえ」を選択すると、"
"アップグレードはキャンセルされます。"

#: ../DistUpgrade/DistUpgradeController.py:844
#: ../DistUpgrade/DistUpgradeController.py:850
msgid "Repository information invalid"
msgstr "リポジトリ情報が無効です"

#: ../DistUpgrade/DistUpgradeController.py:845
msgid ""
"Upgrading the repository information resulted in a invalid file so a bug "
"reporting process is being started."
msgstr ""
"リポジトリの情報を更新した際にファイルが破損しました。それによりバグ報告のプ"
"ロセスが開始されました。"

#: ../DistUpgrade/DistUpgradeController.py:851
msgid ""
"Upgrading the repository information resulted in a invalid file. To report a "
"bug install apport and then execute 'apport-bug ubuntu-release-upgrader'."
msgstr ""
"リポジトリ情報の更新を行いましたがファイルが無効です。バグ報告するには、"
"apportをインストールしてから'apport-bug ubuntu-release-upgrader'を実行してく"
"ださい。"

#: ../DistUpgrade/DistUpgradeController.py:860
msgid "Third party sources disabled"
msgstr "サードパーティが提供するリポジトリを使わない設定にしました"

#: ../DistUpgrade/DistUpgradeController.py:861
msgid ""
"Some third party entries in your sources.list were disabled. You can re-"
"enable them after the upgrade with the 'software-properties' tool or your "
"package manager."
msgstr ""
"sources.list にあるサードパーティが提供するリポジトリを使わない設定にしまし"
"た。アップグレード完了後、'ソフトウェアソース' ツールもしくはパッケージマネー"
"ジャーを使って再び利用可能な設定にすることができます。"

#: ../DistUpgrade/DistUpgradeController.py:903
msgid "Package in inconsistent state"
msgid_plural "Packages in inconsistent state"
msgstr[0] "矛盾した状態のパッケージ"

#: ../DistUpgrade/DistUpgradeController.py:906
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Please reinstall the package manually or "
"remove it from the system."
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archive can be found for them. Please reinstall the packages manually "
"or remove them from the system."
msgstr[0] ""
"パッケージ '%s' は 矛盾した状態にあり再インストールが必要ですが、そのための"
"アーカイブを見つけることができません。パッケージを手動で再インストールする"
"か、システムからパッケージを削除してください。"

#: ../DistUpgrade/DistUpgradeController.py:969
msgid "Error during update"
msgstr "アップデート中にエラーが発生しました"

#: ../DistUpgrade/DistUpgradeController.py:970
msgid ""
"A problem occurred during the update. This is usually some sort of network "
"problem, please check your network connection and retry."
msgstr ""
"アップデート中に問題が発生しました。通常、これはネットワークにおける何らかの"
"問題です。ネットワーク接続が可能であることをチェックし、あらためて試してくだ"
"さい。"

#: ../DistUpgrade/DistUpgradeController.py:1013
#: ../DistUpgrade/DistUpgradeController.py:1018
msgid "EFI System Partition (ESP) not usable"
msgstr "EFIシステムパーティション(ESP)を使用できません"

#: ../DistUpgrade/DistUpgradeController.py:1014
msgid ""
"Your EFI System Partition (ESP) is not mounted at /boot/efi. Please ensure "
"that it is properly configured and try again."
msgstr ""
"EFIシステムパーティション(ESP)が /boot/efi にマウントされていません。正しい方"
"法でマウントしてから、もう一度実行してください。"

#: ../DistUpgrade/DistUpgradeController.py:1019
msgid ""
"The EFI System Partition (ESP) mounted at /boot/efi is not writable. Please "
"mount this partition read-write and try again."
msgstr ""
"/boot/efi にマウントされたEFIシステムパーティション(ESP)は書き込み可能ではあ"
"りません。読み込みと書き込みが可能な状態でマウントしてから、もう一度実行して"
"ください。"

#: ../DistUpgrade/DistUpgradeController.py:1026
msgid "Not enough free disk space"
msgstr "ディスクの空き領域が足りません"

#. TRANSLATORS: you can change the order of the sentence,
#. make sure to keep all {str_*} string untranslated.
#: ../DistUpgrade/DistUpgradeController.py:1029
#, python-brace-format
msgid ""
"The upgrade has aborted. The upgrade needs a total of {str_total} free space "
"on disk '{str_dir}'. Please free at least an additional {str_needed} of disk "
"space on '{str_dir}'. {str_remedy}"
msgstr ""
"アップグレードを中断しました。アップグレードには '{str_dir}' に空き領域が "
"{str_total} 必要です。'{str_dir}' の空き領域を少なくとも {str_needed} 確保し"
"てください。{str_remedy}"

#. specific ways to resolve lack of free space
#: ../DistUpgrade/DistUpgradeController.py:1034
msgid ""
"Remove temporary packages of former installations using 'sudo apt clean'."
msgstr ""
"'sudo apt clean' を使って、以前のインストールに利用した一時的なパッケージを削"
"除してください。"

#: ../DistUpgrade/DistUpgradeController.py:1036
msgid ""
"You can remove old kernels using 'sudo apt autoremove' and you could also "
"set COMPRESS=xz in /etc/initramfs-tools/initramfs.conf to reduce the size of "
"your initramfs."
msgstr ""
"'sudo apt autoremove' を使って古いカーネルを削除することや、/etc/initramfs-"
"tools/initramfs.conf に COMPRESS=xz を設定して initramfs のサイズを減らすこと"
"もできます。"

#: ../DistUpgrade/DistUpgradeController.py:1041
msgid ""
"Empty your trash and remove temporary packages of former installations using "
"'sudo apt-get clean'."
msgstr ""
"'sudo apt clean' を使って、以前のインストールに利用した一時的なパッケージを削"
"除し、ゴミ箱も空にしてください。"

#: ../DistUpgrade/DistUpgradeController.py:1044
msgid "Reboot to clean up files in /tmp."
msgstr "再起動し、/tmp にあるファイルをクリーンアップしてください。"

#. calc the dist-upgrade and see if the removals are ok/expected
#. do the dist-upgrade
#: ../DistUpgrade/DistUpgradeController.py:1083
#: ../DistUpgrade/DistUpgradeController.py:1925
#: ../DistUpgrade/DistUpgradeController.py:1977
msgid "Calculating the changes"
msgstr "変更点を確認中"

#. ask the user
#: ../DistUpgrade/DistUpgradeController.py:1127
msgid "Do you want to start the upgrade?"
msgstr "アップグレードを開始しますか？"

#: ../DistUpgrade/DistUpgradeController.py:1146
#, python-format
msgid ""
"Livepatch security updates are not available for Ubuntu %s. If you upgrade, "
"Livepatch will turn off."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1218
msgid "Upgrade canceled"
msgstr "アップグレードをキャンセルしました"

#: ../DistUpgrade/DistUpgradeController.py:1219
msgid ""
"The upgrade will cancel now and the original system state will be restored. "
"You can resume the upgrade at a later time."
msgstr ""
"アップグレードはすぐにキャンセルされ、システムは元の状態に戻ります。後でアッ"
"プグレードをやり直すことができます。"

#: ../DistUpgrade/DistUpgradeController.py:1225
#: ../DistUpgrade/DistUpgradeController.py:1370
msgid "Could not download the upgrades"
msgstr "アップグレードに必要なデータをダウンロードできません"

#: ../DistUpgrade/DistUpgradeController.py:1226
msgid ""
"The upgrade has aborted. Please check your Internet connection or "
"installation media and try again. All files downloaded so far have been kept."
msgstr ""
"アップグレードを中断しました。インターネット接続またはインストールメディアを"
"確認して再度試してください。これまでにダウンロードしたすべてのファイルは保存"
"されています。"

#. FIXME: strings are not good, but we are in string freeze
#. currently
#: ../DistUpgrade/DistUpgradeController.py:1319
#: ../DistUpgrade/DistUpgradeController.py:1358
#: ../DistUpgrade/DistUpgradeController.py:1474
msgid "Error during commit"
msgstr "反映中にエラーが発生しました"

#. generate a new cache
#: ../DistUpgrade/DistUpgradeController.py:1321
#: ../DistUpgrade/DistUpgradeController.py:1360
#: ../DistUpgrade/DistUpgradeController.py:1519
msgid "Restoring original system state"
msgstr "システムを元に戻しています"

#: ../DistUpgrade/DistUpgradeController.py:1322
#: ../DistUpgrade/DistUpgradeController.py:1337
#: ../DistUpgrade/DistUpgradeController.py:1361
msgid "Could not install the upgrades"
msgstr "アップグレードをインストールできません"

#. invoke the frontend now and show a error message
#: ../DistUpgrade/DistUpgradeController.py:1327
msgid ""
"The upgrade has aborted. Your system could be in an unusable state. A "
"recovery will run now (dpkg --configure -a)."
msgstr ""
"アップグレードを中断しました。システムが不安定な状態の可能性があります。今か"
"らリカバリーを実行します。(dpkg --configure -a)"

#: ../DistUpgrade/DistUpgradeController.py:1332
#, python-format
msgid ""
"\n"
"\n"
"Please report this bug in a browser at http://bugs.launchpad.net/ubuntu/"
"+source/ubuntu-release-upgrader/+filebug and attach the files in /var/log/"
"dist-upgrade/ to the bug report.\n"
"%s"
msgstr ""
"\n"
"\n"
"ブラウザから http://bugs.launchpad.net/ubuntu/+source/ubuntu-release-"
"upgrader/+filebug を開き /var/log/dist-upgrade/ にあるファイルを添付し、この"
"バグを報告してください。\n"
"%s"

#: ../DistUpgrade/DistUpgradeController.py:1371
msgid ""
"The upgrade has aborted. Please check your Internet connection or "
"installation media and try again. "
msgstr ""
"アップグレードを中断しました。インターネット接続またはインストールメディアを"
"確認して、もう一度実行してください。 "

#: ../DistUpgrade/DistUpgradeController.py:1399
msgid "Searching for obsolete software"
msgstr "古いソフトウェアを検索しています"

#: ../DistUpgrade/DistUpgradeController.py:1462
msgid "Remove obsolete packages?"
msgstr ""
"サポートが中止された（あるいはリポジトリに存在しない）パッケージを削除します"
"か？"

#: ../DistUpgrade/DistUpgradeController.py:1463
#: ../data/gtkbuilder/DistUpgrade.ui.h:8
msgid "_Keep"
msgstr "そのまま(_K)"

#: ../DistUpgrade/DistUpgradeController.py:1463
msgid "_Remove"
msgstr "削除(_R)"

#: ../DistUpgrade/DistUpgradeController.py:1475
msgid ""
"A problem occurred during the clean-up. Please see the below message for "
"more information. "
msgstr ""
"クリーンアップ中に問題が発生しました。詳細情報は下記のメッセージを参照してく"
"ださい。 "

#. FIXME: instead of error out, fetch and install it
#. here
#: ../DistUpgrade/DistUpgradeController.py:1557
msgid "Required depends is not installed"
msgstr "依存するパッケージがインストールされていません"

#: ../DistUpgrade/DistUpgradeController.py:1558
#, python-format
msgid "The required dependency '%s' is not installed. "
msgstr "依存するパッケージ '%s' がインストールされていません。 "

#. sanity check (check for ubuntu-desktop, brokenCache etc)
#. then open the cache (again)
#: ../DistUpgrade/DistUpgradeController.py:1791
#: ../DistUpgrade/DistUpgradeController.py:1875
msgid "Checking package manager"
msgstr "パッケージマネージャーをチェック中です"

#: ../DistUpgrade/DistUpgradeController.py:1797
#: ../DistUpgrade/DistUpgradeController.py:1803
msgid "Preparing the upgrade failed"
msgstr "アップグレードの準備に失敗しました"

#: ../DistUpgrade/DistUpgradeController.py:1798
msgid ""
"Preparing the system for the upgrade failed so a bug reporting process is "
"being started."
msgstr ""
"アップグレードのための準備に失敗しました。それによりバグ報告のプロセスが開始"
"されました。"

#: ../DistUpgrade/DistUpgradeController.py:1804
msgid ""
"Preparing the system for the upgrade failed. To report a bug install apport "
"and then execute 'apport-bug ubuntu-release-upgrader'."
msgstr ""
"システムのアップグレード準備に失敗しました。バグ報告を行うには apport をイン"
"ストールしてから 'apport-bug ubuntu-release-upgrader' を実行してください。"

#: ../DistUpgrade/DistUpgradeController.py:1821
#: ../DistUpgrade/DistUpgradeController.py:1831
msgid "Getting upgrade prerequisites failed"
msgstr "アップグレードの事前作業に失敗しました"

#: ../DistUpgrade/DistUpgradeController.py:1822
msgid ""
"The system was unable to get the prerequisites for the upgrade. The upgrade "
"will abort now and restore the original system state.\n"
"\n"
"Additionally, a bug reporting process is being started."
msgstr ""
"アップグレードに必要なものを取得できませんでした。アップグレードはすぐに中止"
"され、システムは以前の状態に戻されます。\n"
"\n"
"同時にバグ報告のプロセスが開始されました。"

#: ../DistUpgrade/DistUpgradeController.py:1832
msgid ""
"The system was unable to get the prerequisites for the upgrade. The upgrade "
"will abort now and restore the original system state.\n"
"\n"
"To report a bug install apport and then execute 'apport-bug ubuntu-release-"
"upgrader'."
msgstr ""
"システムはアップグレードの必要条件を整えることができませんでした。アップグ"
"レードは中止され、元のシステムの状態が復元されます。\n"
"\n"
"バグ報告を行うには apport をインストールしてから 'apport-bug ubuntu-release-"
"upgrader' を実行してください。"

#: ../DistUpgrade/DistUpgradeController.py:1866
msgid "Updating repository information"
msgstr "リポジトリ情報のアップデート"

#: ../DistUpgrade/DistUpgradeController.py:1902
msgid "Invalid package information"
msgstr "利用できないパッケージ情報です"

#: ../DistUpgrade/DistUpgradeController.py:1903
#, python-format
msgid ""
"After updating your package information, the essential package '%s' could "
"not be located. This may be because you have no official mirrors listed in "
"your software sources, or because of excessive load on the mirror you are "
"using. See /etc/apt/sources.list for the current list of configured software "
"sources.\n"
"In the case of an overloaded mirror, you may want to try the upgrade again "
"later."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1932
#: ../DistUpgrade/DistUpgradeController.py:2038
msgid "Fetching"
msgstr "取得中"

#: ../DistUpgrade/DistUpgradeController.py:1939
#: ../DistUpgrade/DistUpgradeController.py:1962
#: ../DistUpgrade/DistUpgradeController.py:1992
#: ../DistUpgrade/DistUpgradeController.py:2042
msgid "Upgrading"
msgstr "アップグレード中です"

#: ../DistUpgrade/DistUpgradeController.py:1941
msgid "Upgrade infeasible"
msgstr "アップグレードが実行できません。"

#: ../DistUpgrade/DistUpgradeController.py:1942
msgid ""
"The upgrade could not be completed, there were errors during the upgrade "
"process."
msgstr "作業中に問題が発生したため、アップグレードを完了できませんでした。"

#. don't abort here, because it would restore the sources.list
#: ../DistUpgrade/DistUpgradeController.py:1965
#: ../DistUpgrade/DistUpgradeController.py:1981
msgid "Upgrade incomplete"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1966
#: ../DistUpgrade/DistUpgradeController.py:1982
msgid ""
"The upgrade has partially completed but there were errors during the upgrade "
"process."
msgstr ""
"作業中に問題が発生したため、いくつかのアップグレードを完了できませんでした。"

#. don't abort here, because it would restore the sources.list
#: ../DistUpgrade/DistUpgradeController.py:1997
#: ../DistUpgrade/DistUpgradeController.py:2044
#: ../DistUpgrade/DistUpgradeController.py:2050
#: ../DistUpgrade/DistUpgradeController.py:2061
msgid "Upgrade complete"
msgstr "アップグレードが完了しました"

#: ../DistUpgrade/DistUpgradeController.py:1998
#: ../DistUpgrade/DistUpgradeController.py:2045
#: ../DistUpgrade/DistUpgradeController.py:2051
msgid ""
"The upgrade has completed but there were errors during the upgrade process."
msgstr ""
"アップグレードは完了しましたが、アップグレード中にいくつかのエラーが発生しま"
"した。"

#: ../DistUpgrade/DistUpgradeController.py:2013
msgid "System upgrade is complete."
msgstr "システムのアップグレードが完了しました。"

#: ../DistUpgrade/DistUpgradeController.py:2062
msgid "The partial upgrade was completed."
msgstr "部分的なアップグレードが完了しました。"

#: ../DistUpgrade/DistUpgradeController.py:2091
msgid "Lock screen disabled"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:2092
msgid ""
"Your lock screen has been disabled and will remain disabled until you reboot."
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcher.py:107
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:170
msgid "Could not find the release notes"
msgstr "リリースノートが見つかりません"

#: ../DistUpgrade/DistUpgradeFetcher.py:108
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:171
msgid "The server may be overloaded. "
msgstr "サーバーに大きな負荷がかかっています。 "

#: ../DistUpgrade/DistUpgradeFetcher.py:120
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:175
msgid "Could not download the release notes"
msgstr "リリースノートをダウンロードできません"

#: ../DistUpgrade/DistUpgradeFetcher.py:121
#: ../DistUpgrade/DistUpgradeFetcherCore.py:75
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:176
msgid "Please check your internet connection."
msgstr "インターネット接続を確認してください。"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:70
#, fuzzy
msgid "Could not find the release announcement"
msgstr "リリースノートが見つかりません"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:71
#, fuzzy
msgid "The server may be overloaded."
msgstr "サーバーに大きな負荷がかかっています。 "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:74
#, fuzzy
msgid "Could not download the release announcement"
msgstr "リリースノートをダウンロードできません"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:80
#: ../DistUpgrade/DistUpgradeViewText.py:215
#: ../DistUpgrade/DistUpgradeViewText.py:253
#: ../DistUpgrade/DistUpgradeViewText.py:261
msgid "Continue [yN] "
msgstr "続行する[yN] "

#. TRANSLATORS: the "y" is "yes"
#. TRANSLATORS: first letter of a positive (yes) answer
#: ../DistUpgrade/DistUpgradeFetcherCore.py:82
#: ../DistUpgrade/DistUpgradeViewText.py:219
#: ../DistUpgrade/DistUpgradeViewText.py:264
msgid "y"
msgstr "y"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:99
#, python-format
msgid "authenticate '%(file)s' against '%(signature)s' "
msgstr "「%(signature)s」を用いて「%(file)s」の認証を行ないます "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:125
#, python-format
msgid "extracting '%s'"
msgstr "'%s' の展開中"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:146
#: ../DistUpgrade/DistUpgradeFetcherCore.py:147
msgid "Could not run the upgrade tool"
msgstr "アップグレード・ツールを実行できません"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:148
msgid ""
"This is most likely a bug in the upgrade tool. Please report it as a bug "
"using the command 'ubuntu-bug ubuntu-release-upgrader-core'."
msgstr ""
"これはアップグレードツールのバグと思われます。これを 'ubuntu-bug ubuntu-"
"release-upgrader-core' というコマンドを実行してバグとして報告してください。"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:225
msgid "Upgrade tool signature"
msgstr "ツールの署名のアップグレード"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:232
msgid "Upgrade tool"
msgstr "ツールのアップグレード"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:266
msgid "Failed to fetch"
msgstr "取得に失敗しました"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:267
msgid "Fetching the upgrade failed. There may be a network problem. "
msgstr "アップグレードの取得に失敗しました。おそらくネットワークの問題です。 "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:271
msgid "Authentication failed"
msgstr "認証に失敗しました"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:272
msgid ""
"Authenticating the upgrade failed. There may be a problem with the network "
"or with the server. "
msgstr ""
"アップグレードの認証に失敗しました。おそらくネットワークまたはサーバーの問題"
"です。 "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:277
msgid "Failed to extract"
msgstr "抽出に失敗しました"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:278
msgid ""
"Extracting the upgrade failed. There may be a problem with the network or "
"with the server. "
msgstr ""
"アップグレードの展開に失敗しました。おそらくネットワークまたはサーバーの問題"
"です。 "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:283
msgid "Verification failed"
msgstr "認証に失敗しました"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:284
msgid ""
"Verifying the upgrade failed.  There may be a problem with the network or "
"with the server. "
msgstr ""
"アップグレードの検証に失敗しました。ネットワーク接続もしくはサーバーに問題が"
"あるかもしれません。 "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:298
#: ../DistUpgrade/DistUpgradeFetcherCore.py:304
msgid "Can not run the upgrade"
msgstr "アップグレードを実行できません"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:299
msgid ""
"This usually is caused by a system where /tmp is mounted noexec. Please "
"remount without noexec and run the upgrade again."
msgstr ""
"この現象は、通常/tmpがnoexecでマウントされている場合にシステムで発生します。"
"noexecを付けずに再マウントして、再度アップグレードを実行してください。"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:305
#, python-format
msgid "The error message is '%s'."
msgstr "エラーメッセージは'%s'です。"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:151
msgid "&Upgrade"
msgstr "アップグレード(&U)"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:154
#: ../DistUpgrade/DistUpgradeViewKDE.py:715
msgid "&Cancel"
msgstr "キャンセル(&C)"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:156
#: ../data/gtkbuilder/ReleaseNotes.ui.h:1
msgid "Release Notes"
msgstr "リリースノート"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:191
msgid "Upgrade"
msgstr "アップグレード"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:207
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:222
msgid "Downloading additional package files..."
msgstr "追加パッケージのダウンロード..."

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:224
#, python-format
msgid "File %s of %s at %sB/s"
msgstr "ファイル %s / %s (%sB/s)"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:228
#, python-format
msgid "File %s of %s"
msgstr "ファイル %s / %s"

#. print("mediaChange %s %s" % (medium, drive))
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:235
#: ../DistUpgrade/DistUpgradeViewGtk3.py:125
#: ../DistUpgrade/DistUpgradeViewKDE.py:302
#, python-format
msgid "Please insert '%s' into the drive '%s'"
msgstr "メディア '%s' をドライブ '%s' に挿入してください"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:237
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:242
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:243
#: ../DistUpgrade/DistUpgradeViewKDE.py:303
msgid "Media Change"
msgstr "メディアの交換"

#: ../DistUpgrade/DistUpgradeQuirks.py:230
msgid "Your graphics hardware may not be fully supported in Ubuntu 14.04."
msgstr ""
"あなたが使用中のグラフィックハードウェアはUbuntu 14.04では完全にサポートされ"
"ない場合があります。"

#: ../DistUpgrade/DistUpgradeQuirks.py:232
msgid ""
"Running the 'unity' desktop environment is not fully supported by your "
"graphics hardware. You will maybe end up in a very slow environment after "
"the upgrade. Our advice is to keep the LTS version for now. For more "
"information see https://wiki.ubuntu.com/X/Bugs/"
"UpdateManagerWarningForUnity3D Do you still want to continue with the "
"upgrade?"
msgstr ""
"'unity' デスクトップ環境は、お使いのグラフィックハードウェアによるサポートが"
"不完全です。アップグレード後にとても遅い環境になるかもしれません。現時点での"
"私たちのアドバイスは、LTSバージョンのままにしておくことです。詳細は https://"
"wiki.ubuntu.com/X/Bugs/UpdateManagerWarningForUnity3D を確認してください。そ"
"れでもアップグレードを続けますか？"

#: ../DistUpgrade/DistUpgradeQuirks.py:256
msgid "Your graphics hardware may not be fully supported in Ubuntu 12.04 LTS."
msgstr ""
"現在使用中のグラフィックハードウェアのサポートは Ubuntu 12.04 LTS では不完全"
"な可能性があります。"

#: ../DistUpgrade/DistUpgradeQuirks.py:258
msgid ""
"The support in Ubuntu 12.04 LTS for your Intel graphics hardware is limited "
"and you may encounter problems after the upgrade. For more information see "
"https://wiki.ubuntu.com/X/Bugs/UpdateManagerWarningForI8xx Do you want to "
"continue with the upgrade?"
msgstr ""
"現在使用中の Intel 製グラフィックハードウェアは Ubuntu 12.04 LTS では制限付き"
"のサポートとなっているため、アップグレード後に不具合が発生する可能性がありま"
"す。詳しくは https://wiki.ubuntu.com/X/Bugs/UpdateManagerWarningForI8xx をご"
"覧ください。アップグレードを続行しますか?"

#: ../DistUpgrade/DistUpgradeQuirks.py:278
msgid ""
"Upgrading may reduce desktop effects, and performance in games and other "
"graphically intensive programs."
msgstr ""
"アップグレードによって、デスクトップ効果（3Dデスクトップ）やゲーム、グラ"
"フィックに強く依存するその他のプログラムなどのパフォーマンスが低下するかもし"
"れません。"

#: ../DistUpgrade/DistUpgradeQuirks.py:282
msgid ""
"This computer is currently using the AMD 'fglrx' graphics driver. No version "
"of this driver is available that works with your hardware in Ubuntu 10.04 "
"LTS.\n"
"\n"
"Do you want to continue?"
msgstr ""
"現在、このコンピューターはAMD 'fglrx' グラフィックドライバーを利用していま"
"す。Ubuntu 10.04 LTS では、このハードウェアで動作可能なドライバーのバージョン"
"はありません。\n"
"\n"
"作業を続けますか？"

#: ../DistUpgrade/DistUpgradeQuirks.py:321
msgid "Sorry, no more upgrades for this system"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:322
#, python-format
msgid ""
"There will not be any further Ubuntu releases for this system's 'i386' "
"architecture.\n"
"\n"
"Updates for Ubuntu %s will continue until %s."
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:337
msgid "No ARMv6 CPU"
msgstr "ARMv6 準拠ではない CPU です"

#: ../DistUpgrade/DistUpgradeQuirks.py:338
msgid ""
"Your system uses an ARM CPU that is older than the ARMv6 architecture. All "
"packages in karmic were built with optimizations requiring ARMv6 as the "
"minimal architecture. It is not possible to upgrade your system to a new "
"Ubuntu release with this hardware."
msgstr ""
"このシステムでは ARM CPU が使われていますが、ARMv6 アーキテクチャより古いもの"
"のようです。karmic の全てのパッケージは、ARMv6 アーキテクチャへの対応が必須な"
"最適化オプションを利用してビルドされています。このハードウェアでは新しい "
"Ubuntu のリリースにアップグレードできません。"

#: ../DistUpgrade/DistUpgradeQuirks.py:358
msgid ""
"Sorry, this storage driver is not supported in kernels for newer releases"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:360
#, python-format
msgid ""
"There will not be any further Ubuntu releases that provide kernel support "
"for the aufs storage driver.\n"
"\n"
"Please ensure that none of your containers are using the aufs storage "
"driver, remove the directory %s and try again."
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:380
msgid "No init available"
msgstr "initデーモンが見つかりません"

#: ../DistUpgrade/DistUpgradeQuirks.py:381
msgid ""
"Your system appears to be a virtualised environment without an init daemon, "
"e.g. Linux-VServer. Ubuntu 10.04 LTS cannot function within this type of "
"environment, requiring an update to your virtual machine configuration "
"first.\n"
"\n"
"Are you sure you want to continue?"
msgstr ""
"このシステムは、initデーモンの関与なしで稼働している仮想環境のようです（例："
"Linux-VServer）。 Ubuntu 10.04 LTS ではこのタイプの環境を稼働させることができ"
"ません。アップグレードの前に、仮想マシン設定を設定しなおす必要があります。\n"
"\n"
"本当に作業を進めてよろしいですか？"

#: ../DistUpgrade/DistUpgradeQuirks.py:422
msgid "The Robot Operating System (ROS) is installed"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:423
msgid ""
"It appears that ROS is currently installed. Each ROS release is very strict "
"about the versions of Ubuntu it supports, and Ubuntu upgrades can fail if "
"that guidance isn't followed. Before continuing, please either uninstall "
"ROS, or ensure the ROS release you have installed supports the version of "
"Ubuntu to which you're upgrading.\n"
"\n"
"For ROS 1 releases, refer to REP 3:\n"
"https://www.ros.org/reps/rep-0003.html\n"
"\n"
"For ROS 2 releases, refer to REP 2000:\n"
"https://www.ros.org/reps/rep-2000.html\n"
"\n"
"Are you sure you want to continue?"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:554
#, fuzzy
msgid "Connection to the Snap Store failed"
msgstr "Snap Store への接続に失敗しました"

#: ../DistUpgrade/DistUpgradeQuirks.py:555
msgid ""
"You have the package lxd installed but your system is unable to reach the "
"Snap Store. lxd is now provided via a snap and the release upgrade will fail "
"if snapd is not functional. Please make sure you're connected to the "
"Internet and update any firewall or proxy settings as needed so that you can "
"reach api.snapcraft.io. If you are an enterprise with a firewall setup you "
"may want to configure a Snap Store proxy."
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:570
msgid "Connection to Snap Store failed"
msgstr "Snap Store への接続に失敗しました"

#: ../DistUpgrade/DistUpgradeQuirks.py:571
msgid ""
"Your system does not have a connection to the Snap Store. For the best "
"upgrade experience make sure that your system can connect to api.snapcraft."
"io.\n"
"Do you still want to continue with the upgrade?"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:580
msgid "Outdated snapd package"
msgstr "期限切れの snapd パッケージ"

#: ../DistUpgrade/DistUpgradeQuirks.py:581
msgid ""
"Your system does not have the latest version of snapd. Please update the "
"version of snapd on your system to improve the upgrade experience.\n"
"Do you still want to continue with the upgrade?"
msgstr ""

#. now perform direct API calls to the store, requesting size
#. information for each of the snaps needing installation
#: ../DistUpgrade/DistUpgradeQuirks.py:604
msgid "Calculating snap size requirements"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:635
msgid "Processing snap replacements"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:641
#, python-format
msgid "refreshing snap %s"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:645
#, python-format
msgid "removing snap %s"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:648
#, python-format
msgid "installing snap %s"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:677
msgid "PAE not enabled"
msgstr "PAEが有効になっていません"

#: ../DistUpgrade/DistUpgradeQuirks.py:678
msgid ""
"Your system uses a CPU that does not have PAE enabled. Ubuntu only supports "
"non-PAE systems up to Ubuntu 12.04. To upgrade to a later version of Ubuntu, "
"you must enable PAE (if this is possible) see:\n"
"http://help.ubuntu.com/community/EnablingPAE"
msgstr ""
"お使いのシステムではPAEが有効なCPUが利用されていません。UbuntuはPAE非対応シス"
"テムをUbuntu 12.04までしかサポートしていません。新しいバージョンのUbuntuに"
"アップグレードするには、PAEを有効にする必要があります。(可能であれば)次をご覧"
"ください: http://help.ubuntu.com/community/EnablingPAE"

#: ../DistUpgrade/DistUpgradeQuirks.py:1050
msgid "Checking for installed snaps"
msgstr ""

#: ../DistUpgrade/DistUpgradeMain.py:62
msgid ""
"Use frontend. Currently available: \n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKDE"
msgstr ""
"フロントエンドを使用してください。現在利用可能なもの: \n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKDE"

#: ../DistUpgrade/DistUpgradeMain.py:65
msgid "*DEPRECATED* this option will be ignored"
msgstr "*DEPRECATED* このオプションは無視されます"

#: ../DistUpgrade/DistUpgradeMain.py:68
msgid "Perform a partial upgrade only (no sources.list rewriting)"
msgstr "部分アップグレードだけを実行します（sources.listを書き換えません）"

#: ../DistUpgrade/DistUpgradeMain.py:71
msgid "Disable GNU screen support"
msgstr "GNU screen のサポートを無効にする"

#: ../DistUpgrade/DistUpgradeMain.py:73
msgid "Set datadir"
msgstr "datadirを設定"

#: ../DistUpgrade/DistUpgradeMain.py:76
msgid "Upgrade to the development release"
msgstr "開発リリースにアップグレードする"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:146
#: ../DistUpgrade/DistUpgradeViewKDE.py:316
msgid "Fetching is complete"
msgstr "取得が完了しました"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:161
#: ../DistUpgrade/DistUpgradeViewKDE.py:332
#, python-format
msgid "Fetching file %li of %li at %sB/s"
msgstr "%li / %li を取得中（%s B/s）"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:163
#: ../DistUpgrade/DistUpgradeViewGtk3.py:325
#: ../DistUpgrade/DistUpgradeViewKDE.py:333
#: ../DistUpgrade/DistUpgradeViewKDE.py:483
#, python-format
msgid "About %s remaining"
msgstr "残り時間 約%s"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:166
#: ../DistUpgrade/DistUpgradeViewKDE.py:335
#, python-format
msgid "Fetching file %li of %li"
msgstr "%li / %li を取得中です"

#. FIXME: add support for the timeout
#. of the terminal (to display something useful then)
#. -> longer term, move this code into python-apt
#: ../DistUpgrade/DistUpgradeViewGtk3.py:198
#: ../DistUpgrade/DistUpgradeViewKDE.py:373
msgid "Applying changes"
msgstr "変更を適用しています"

#. we do not report followup errors from earlier failures
#: ../DistUpgrade/DistUpgradeViewGtk3.py:224
#: ../DistUpgrade/DistUpgradeViewKDE.py:386
msgid "dependency problems - leaving unconfigured"
msgstr "依存関係の問題 - 設定を見送ります"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:229
#: ../DistUpgrade/DistUpgradeViewKDE.py:388
#, python-format
msgid "Could not install '%s'"
msgstr "'%s' がインストールできません"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:230
#: ../DistUpgrade/DistUpgradeViewKDE.py:389
#, python-format
msgid ""
"The upgrade will continue but the '%s' package may not be in a working "
"state. Please consider submitting a bug report about it."
msgstr ""
"アップグレードを続けますが、'%s' パッケージが動かない状態にある可能性がありま"
"す。この件に関してバグレポートを送信することを検討してください。"

#. self.expander.set_expanded(True)
#: ../DistUpgrade/DistUpgradeViewGtk3.py:247
#: ../DistUpgrade/DistUpgradeViewKDE.py:411
#, python-format
msgid ""
"Replace the customized configuration file\n"
"'%s'?"
msgstr ""
"以下のカスタマイズ済みの設定ファイルを置き換えますか？\n"
"'%s'"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:248
#: ../DistUpgrade/DistUpgradeViewKDE.py:412
msgid ""
"You will lose any changes you have made to this configuration file if you "
"choose to replace it with a newer version."
msgstr ""
"より新しいバージョンと入れ換えた場合、この構成ファイルへの変更内容は失われま"
"す。"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:268
#: ../DistUpgrade/DistUpgradeViewKDE.py:435
msgid "The 'diff' command was not found"
msgstr "'diff' コマンドが見つかりません"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:535
#: ../DistUpgrade/DistUpgradeViewText.py:140
msgid "A fatal error occurred"
msgstr "致命的なエラーが起こりました"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:536
msgid ""
"Please report this as a bug (if you haven't already) and include the files /"
"var/log/dist-upgrade/main.log and /var/log/dist-upgrade/apt.log in your "
"report. The upgrade has aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""
"（まだ報告されていなければ）この現象をバグとして報告してください。報告には /"
"var/log/dist-upgrade/main.log と /var/log/dist-upgrade/apt.log を添付する必要"
"があります。アップグレードは完了しませんでした。\n"
"変更前のsources.listは/etc/apt/sources.list.distUpgradeに保存されています。"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:566
msgid "Ctrl-c pressed"
msgstr "Ctrl-c が入力されました"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:567
msgid ""
"This will abort the operation and may leave the system in a broken state. "
"Are you sure you want to do that?"
msgstr ""
"これは操作を中断することになり、システムを壊れた状態にしてしまうかもしれませ"
"ん。本当に実行しますか？"

#. append warning
#: ../DistUpgrade/DistUpgradeViewGtk3.py:706
msgid "To prevent data loss close all open applications and documents."
msgstr ""
"データが失われることを避けるため、利用中のアプリケーションとドキュメントを閉"
"じてください。"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:720
#, python-format
msgid "No longer supported by Canonical (%s)"
msgstr "Canonical によってサポートされなくなりました (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:721
#, python-format
msgid "<b>Downgrade (%s)</b>"
msgstr "<b>ダウングレード (%s)</b>"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:722
#, python-format
msgid "Remove (%s)"
msgstr "削除 (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:723
#, python-format
msgid "No longer needed (%s)"
msgstr "もう不要なもの (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:724
#, python-format
msgid "Install (%s)"
msgstr "インストール (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:725
#, python-format
msgid "Upgrade (%s)"
msgstr "アップグレード (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:773
msgid "Cancel"
msgstr "キャンセル"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:774
#: ../DistUpgrade/DistUpgradeViewKDE.py:939
msgid "Continue"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:447
msgid "Show Difference >>>"
msgstr "差分を表示 >>>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:450
msgid "<<< Hide Difference"
msgstr "<<< 差分を隠す"

#: ../DistUpgrade/DistUpgradeViewKDE.py:701
msgid "Error"
msgstr "エラー"

#: ../DistUpgrade/DistUpgradeViewKDE.py:719
#: ../DistUpgrade/DistUpgradeViewKDE.py:960
msgid "&Close"
msgstr "閉じる(&C)"

#: ../DistUpgrade/DistUpgradeViewKDE.py:753
msgid "Show Terminal >>>"
msgstr "端末を表示 >>>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:756
msgid "<<< Hide Terminal"
msgstr "<<< 端末を隠す"

#: ../DistUpgrade/DistUpgradeViewKDE.py:829
msgid "Information"
msgstr "情報"

#: ../DistUpgrade/DistUpgradeViewKDE.py:877
msgid "&Start Upgrade"
msgstr "アップグレードの開始(&S)"

#: ../DistUpgrade/DistUpgradeViewKDE.py:879
#: ../DistUpgrade/DistUpgradeViewKDE.py:923
#: ../DistUpgrade/DistUpgradeViewKDE.py:926
#: ../data/gtkbuilder/DistUpgrade.ui.h:7
msgid "Details"
msgstr "詳細"

#: ../DistUpgrade/DistUpgradeViewKDE.py:901
#, python-format
msgid "No longer supported %s"
msgstr "サポートされなくなりました %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:903
#, python-format
msgid "Remove %s"
msgstr "%s を削除"

#: ../DistUpgrade/DistUpgradeViewKDE.py:905
#: ../DistUpgrade/DistUpgradeViewText.py:239
#, python-format
msgid "Remove (was auto installed) %s"
msgstr "(自動インストールされた) %s を削除"

#: ../DistUpgrade/DistUpgradeViewKDE.py:907
#, python-format
msgid "Install %s"
msgstr "インストール %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:909
#, python-format
msgid "Upgrade %s"
msgstr "アップグレード %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:956
#: ../DistUpgrade/DistUpgradeViewText.py:292
msgid "Restart required"
msgstr "再起動が必要です"

#: ../DistUpgrade/DistUpgradeViewKDE.py:956
msgid "<b><big>Restart the system to complete the upgrade</big></b>"
msgstr ""
"<b><big>アップグレードを完了するには、システムの再起動が必要です</big></b>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:959
#: ../data/gtkbuilder/DistUpgrade.ui.h:14
msgid "_Restart Now"
msgstr "すぐに再起動(_R)"

#. FIXME make this user friendly
#: ../DistUpgrade/DistUpgradeViewKDE.py:977
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly advised to resume the upgrade."
msgstr ""
"<b><big>実行中のアップグレードをキャンセルしますか？</big></b>\n"
"\n"
"アップグレードをキャンセルしてしまうと、システムが不安定な状態になる恐れがあ"
"ります。アップグレードを再開することを強くお勧めします。"

#: ../DistUpgrade/DistUpgradeViewKDE.py:981
msgid "Cancel Upgrade?"
msgstr "アップグレードをキャンセルしますか?"

#: ../DistUpgrade/DistUpgradeView.py:82
#, python-format
msgid "%li day"
msgid_plural "%li days"
msgstr[0] "%li 日"

#: ../DistUpgrade/DistUpgradeView.py:84
#, python-format
msgid "%li hour"
msgid_plural "%li hours"
msgstr[0] "%li 時間"

#: ../DistUpgrade/DistUpgradeView.py:86
#, python-format
msgid "%li minute"
msgid_plural "%li minutes"
msgstr[0] "%li 分"

#: ../DistUpgrade/DistUpgradeView.py:87
#, python-format
msgid "%li second"
msgid_plural "%li seconds"
msgstr[0] "%li 秒"

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_days)s %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#.
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#.
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:103
#, python-format
msgid "%(str_days)s %(str_hours)s"
msgstr "%(str_days)s %(str_hours)s"

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#.
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#.
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:121
#, python-format
msgid "%(str_hours)s %(str_minutes)s"
msgstr "%(str_hours)s %(str_minutes)s"

#. 56 kbit
#. 1Mbit = 1024 kbit
#: ../DistUpgrade/DistUpgradeView.py:172
#, python-format
msgid ""
"This download will take about %s with a 1Mbit DSL connection and about %s "
"with a 56k modem."
msgstr ""
"このダウンロードは 1Mbit DSL 接続で約 %s 、56k モデムで約 %s かかります。"

#. if we have a estimated speed, use it
#: ../DistUpgrade/DistUpgradeView.py:176
#, python-format
msgid "This download will take about %s with your connection. "
msgstr "このダウンロードは約 %s かかります。 "

#. Declare these translatable strings from the .ui files here so that
#. xgettext picks them up.
#: ../DistUpgrade/DistUpgradeView.py:270 ../data/gtkbuilder/DistUpgrade.ui.h:22
msgid "Preparing to upgrade"
msgstr "アップグレードの準備"

#: ../DistUpgrade/DistUpgradeView.py:271
msgid "Getting new software channels"
msgstr "新しいソフトウェア・チャンネルの取得"

#: ../DistUpgrade/DistUpgradeView.py:272 ../data/gtkbuilder/DistUpgrade.ui.h:24
msgid "Getting new packages"
msgstr "新しいパッケージの取得"

#: ../DistUpgrade/DistUpgradeView.py:273 ../data/gtkbuilder/DistUpgrade.ui.h:27
msgid "Installing the upgrades"
msgstr "アップグレードのインストール"

#: ../DistUpgrade/DistUpgradeView.py:274 ../data/gtkbuilder/DistUpgrade.ui.h:26
msgid "Cleaning up"
msgstr "クリーンアップ"

#: ../DistUpgrade/DistUpgradeView.py:363
#, python-format
msgid ""
"%(amount)d installed package is no longer supported by Canonical. You can "
"still get support from the community."
msgid_plural ""
"%(amount)d installed packages are no longer supported by Canonical. You can "
"still get support from the community."
msgstr[0] ""
"%(amount)d 個のインストール済みパッケージは Canonical によってサポートされな"
"くなりました。ただしコミュニティからのサポートは受けることができます。"

#. FIXME: make those two separate lines to make it clear
#. that the "%" applies to the result of ngettext
#: ../DistUpgrade/DistUpgradeView.py:372
#, python-format
msgid "%d package is going to be removed."
msgid_plural "%d packages are going to be removed."
msgstr[0] "%d 個のパッケージが削除されます。"

#: ../DistUpgrade/DistUpgradeView.py:377
#, python-format
msgid "%d new package is going to be installed."
msgid_plural "%d new packages are going to be installed."
msgstr[0] "%d 個の新規パッケージがインストールされます。"

#: ../DistUpgrade/DistUpgradeView.py:383
#, python-format
msgid "%d package is going to be upgraded."
msgid_plural "%d packages are going to be upgraded."
msgstr[0] "%d 個のパッケージがアップグレードされます。"

#: ../DistUpgrade/DistUpgradeView.py:391
#, python-format
msgid ""
"\n"
"\n"
"You have to download a total of %s. "
msgstr ""
"\n"
"\n"
"合計 %s をダウンロードする必要があります。 "

#: ../DistUpgrade/DistUpgradeView.py:396
msgid ""
"Installing the upgrade can take several hours. Once the download has "
"finished, the process cannot be canceled."
msgstr ""
"アップグレードをインストールするのに数時間かかることがあります。ダウンロード"
"が完了してしまうと、処理はキャンセルできません。"

#: ../DistUpgrade/DistUpgradeView.py:400
msgid ""
"Fetching and installing the upgrade can take several hours. Once the "
"download has finished, the process cannot be canceled."
msgstr ""
"アップグレードの取得とインストールには数時間かかることがあります。ダウンロー"
"ドが完了してしまうと、処理はキャンセルできません。"

#: ../DistUpgrade/DistUpgradeView.py:405
msgid "Removing the packages can take several hours. "
msgstr "パッケージの削除に数時間かかることがあります。 "

#. FIXME: this should go into DistUpgradeController
#: ../DistUpgrade/DistUpgradeView.py:410
msgid "The software on this computer is up to date."
msgstr "このコンピューターのソフトウェアは最新です。"

#: ../DistUpgrade/DistUpgradeView.py:411
msgid ""
"There are no upgrades available for your system. The upgrade will now be "
"canceled."
msgstr ""
"システムに適用可能なアップグレードはありません。アップグレードは中止されま"
"す。"

#: ../DistUpgrade/DistUpgradeView.py:427
msgid "Reboot required"
msgstr "再起動が必要です"

#: ../DistUpgrade/DistUpgradeView.py:428
msgid ""
"The upgrade is finished and a reboot is required. Do you want to do this now?"
msgstr ""
"アップグレードが終了しました。再起動が必要です。今すぐ自動で再起動しますか？"

#: ../DistUpgrade/DistUpgradeViewText.py:82
#, python-format
msgid "Progress: [%3i%%]"
msgstr "進捗: [%3i%%]"

#: ../DistUpgrade/DistUpgradeViewText.py:141
msgid ""
"Please report this as a bug and include the files /var/log/dist-upgrade/main."
"log and /var/log/dist-upgrade/apt.log in your report. The upgrade has "
"aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""
"この現象をバグとして報告してください。報告には /var/log/dist-upgrade/main."
"log と /var/log/dist-upgrade/apt.log を添付する必要があります。アップグレード"
"は完了しませんでした。\n"
"変更前のsources.listは/etc/apt/sources.list.distUpgradeに保存されています。"

#: ../DistUpgrade/DistUpgradeViewText.py:165
msgid "Aborting"
msgstr "中断します"

#: ../DistUpgrade/DistUpgradeViewText.py:171
msgid "Demoted:\n"
msgstr "サポートレベルの格下げ:\n"

#: ../DistUpgrade/DistUpgradeViewText.py:178
msgid "To continue please press [ENTER]"
msgstr "続けるには [ENTER] キーを押してください"

#: ../DistUpgrade/DistUpgradeViewText.py:215
#: ../DistUpgrade/DistUpgradeViewText.py:253
msgid "Details [d]"
msgstr "詳細 [d]"

#. TRANSLATORS: the "n" is "no"
#. TRANSLATORS: first letter of a negative (no) answer
#: ../DistUpgrade/DistUpgradeViewText.py:222
#: ../DistUpgrade/DistUpgradeViewText.py:271
msgid "n"
msgstr "n"

#. TRANSLATORS: the "d" is "details"
#: ../DistUpgrade/DistUpgradeViewText.py:225
msgid "d"
msgstr "d"

#: ../DistUpgrade/DistUpgradeViewText.py:230
#, python-format
msgid "No longer supported: %s\n"
msgstr "サポートされなくなりました: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:235
#, python-format
msgid "Remove: %s\n"
msgstr "削除: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:245
#, python-format
msgid "Install: %s\n"
msgstr "インストール: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:250
#, python-format
msgid "Upgrade: %s\n"
msgstr "アップグレード: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:268
msgid "Continue [Yn] "
msgstr "続ける [Yn] "

#: ../DistUpgrade/DistUpgradeViewText.py:293
msgid ""
"To finish the upgrade, a restart is required.\n"
"If you select 'y' the system will be restarted."
msgstr ""
"アップグレードを完了するには再起動が必要です。\n"
"'Y' を選択すると再起動します。"

#: ../DistUpgrade/GtkProgress.py:71
#, python-format
msgid "Downloading file %(current)li of %(total)li with %(speed)s/s"
msgstr "ファイル %(current)li / %(total)li をダウンロード中 (%(speed)s/秒)"

#: ../DistUpgrade/GtkProgress.py:77
#, python-format
msgid "Downloading file %(current)li of %(total)li"
msgstr "ファイル %(current)li / %(total)li をダウンロード中"

#: ../data/gtkbuilder/AcquireProgress.ui.h:1
#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:7
msgid "Show progress of individual files"
msgstr "個別のファイルの進捗を表示"

#: ../data/gtkbuilder/DistUpgrade.ui.h:1
msgid "_Cancel Upgrade"
msgstr "アップグレードをキャンセル(_C)"

#: ../data/gtkbuilder/DistUpgrade.ui.h:2
msgid "_Resume Upgrade"
msgstr "アップグレードを再開(_R)"

#: ../data/gtkbuilder/DistUpgrade.ui.h:3
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly adviced to resume the upgrade."
msgstr ""
"<b><big>アップグレードをキャンセルしますか？</big></b>\n"
"\n"
"アップグレードをキャンセルすると、おそらくシステムは不安定な状態になります。"
"アップグレードを再開することを強くおすすめします。"

#: ../data/gtkbuilder/DistUpgrade.ui.h:6
msgid "_Start Upgrade"
msgstr "アップグレードを開始(_S)"

#: ../data/gtkbuilder/DistUpgrade.ui.h:9
msgid "_Replace"
msgstr "置き換える(_R)"

#: ../data/gtkbuilder/DistUpgrade.ui.h:10
msgid "Difference between the files"
msgstr "ファイル同士の差異"

#: ../data/gtkbuilder/DistUpgrade.ui.h:11
msgid "_Report Bug"
msgstr "バグを報告する(_R)"

#: ../data/gtkbuilder/DistUpgrade.ui.h:12
msgid "_Continue"
msgstr "続行する(_C)"

#: ../data/gtkbuilder/DistUpgrade.ui.h:13
msgid "<b><big>Start the upgrade?</big></b>"
msgstr "<b><big>アップグレードを開始しますか？</big></b>"

#: ../data/gtkbuilder/DistUpgrade.ui.h:15
msgid ""
"<b><big>Restart the system to complete the upgrade</big></b>\n"
"\n"
"Please save your work before continuing."
msgstr ""
"<b><big>アップグレードを完了するには再起動してください</big></b>\n"
"\n"
"先へ進む前に、他のアプリケーションで行っているすべての作業を保存してくださ"
"い。"

#: ../data/gtkbuilder/DistUpgrade.ui.h:18
msgid "Distribution Upgrade"
msgstr "ディストリビューションのアップグレード"

#: ../data/gtkbuilder/DistUpgrade.ui.h:20
#, no-c-format
msgid "<b><big>Upgrading Ubuntu to version %s</big></b>"
msgstr "<b><big>Ubuntuをバージョン%sにアップグレードしています</big></b>"

#: ../data/gtkbuilder/DistUpgrade.ui.h:21
msgid "    "
msgstr "    "

#: ../data/gtkbuilder/DistUpgrade.ui.h:23
msgid "Setting new software channels"
msgstr "新しいソフトウェア・チャンネルを設定しています"

#: ../data/gtkbuilder/DistUpgrade.ui.h:25
msgid "Restarting the computer"
msgstr "コンピューターの再起動"

#: ../data/gtkbuilder/DistUpgrade.ui.h:28
msgid "Terminal"
msgstr "端末"

#: ../data/gtkbuilder/ReleaseNotes.ui.h:2
msgid "_Upgrade"
msgstr "アップグレード(_U)"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:1
msgid "<b>A new version of Ubuntu is available. Would you like to upgrade?</b>"
msgstr ""
"<b>新しいバージョンの Ubuntu が利用可能です。アップグレードしますか?</b>"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:2
msgid "Don't Upgrade"
msgstr "アップグレードしない"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:3
msgid "Ask Me Later"
msgstr "次回にたずねる"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:4
msgid "Yes, Upgrade Now"
msgstr "今すぐアップグレードする"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:5
msgid "You have declined to upgrade to the new Ubuntu"
msgstr "新しいUbuntuへのアップグレードを拒絶"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:6
msgid ""
"You can upgrade at a later time by opening Software Updater and click on "
"\"Upgrade\"."
msgstr ""
"後でアップグレードするには、ソフトウェアアップデーターを開き \"アップグレード"
"\" をクリックします。"

#: ../data/com.ubuntu.release-upgrader.policy.in.h:1
msgid "Perform a release upgrade"
msgstr "リリースアップグレードを実行する"

#: ../data/com.ubuntu.release-upgrader.policy.in.h:2
msgid "To upgrade Ubuntu, you need to authenticate."
msgstr "Ubuntuをアップグレードするには、認証が必要です。"

#: ../data/com.ubuntu.release-upgrader.policy.in.h:3
msgid "Perform a partial upgrade"
msgstr "部分アップグレードを行う"

#: ../data/com.ubuntu.release-upgrader.policy.in.h:4
msgid "To perform a partial upgrade, you need to authenticate."
msgstr "部分的なアップグレードを実行するには、認証が必要です。"

#: ../do-partial-upgrade:75 ../do-release-upgrade:80
msgid "Show version and exit"
msgstr "バージョンを表示して終了"

#: ../do-partial-upgrade:78 ../do-release-upgrade:87
msgid "Directory that contains the data files"
msgstr "データファイルの含まれるディレクトリ"

#: ../do-partial-upgrade:81 ../do-release-upgrade:100
msgid "Run the specified frontend"
msgstr "特定のフロントエンドで実行"

#: ../do-partial-upgrade:112
msgid "Running partial upgrade"
msgstr "部分的なアップグレードを実行"

#: ../do-release-upgrade:34 ../do-release-upgrade:46
msgid "Downloading the release upgrade tool"
msgstr "リリースアップグレードツールのダウンロード"

#: ../do-release-upgrade:83
msgid ""
"If using the latest supported release, upgrade to the development release"
msgstr ""
"サポートされている最新のリリースを使用している場合、開発版リリースにアップグ"
"レードする"

#: ../do-release-upgrade:90 ../check_new_release_gtk.py:186
msgid ""
"Try upgrading to the latest release using the upgrader from $distro-proposed"
msgstr ""
"アップグレードソフトウェアを使って $distro-proposed から最新のリリースへの"
"アップグレードを試す"

#: ../do-release-upgrade:94
msgid ""
"Run in a special upgrade mode.\n"
"Currently 'desktop' for regular upgrades of a desktop system and 'server' "
"for server systems are supported."
msgstr ""
"特別なアップグレードモードで実行する。\n"
"現在、デスクトップシステムの標準的なアップグレードを行う 'desktop' オプション"
"と、サーバーシステム向けの 'server' オプションがサポートされています。"

#: ../do-release-upgrade:103
msgid ""
"Check only if a new distribution release is available and report the result "
"via the exit code"
msgstr ""
"新しいディストリビューション・リリースが利用可能かどうかチェックし、終了コー"
"ドで結果を通知する"

#: ../do-release-upgrade:108
msgid ""
"Try the upgrade with third party mirrors and repositories enabled instead of "
"commenting them out."
msgstr ""

#: ../do-release-upgrade:122
msgid "The options --devel-release and --proposed are"
msgstr "オプション --devel-release および --proposed は"

#: ../do-release-upgrade:123
msgid "mutually exclusive. Please use only one of them."
msgstr "相互に排他的です。どちらか一方のみを使用してください。"

#: ../do-release-upgrade:127
msgid "Checking for a new Ubuntu release"
msgstr "新しい Ubuntu のリリースをチェックしています"

#: ../do-release-upgrade:139
msgid "Your Ubuntu release is not supported anymore."
msgstr "このバージョンのUbuntuは既にサポートが打ち切られています。"

#: ../do-release-upgrade:140
msgid ""
"For upgrade information, please visit:\n"
"%(url)s\n"
msgstr ""
"アップグレード情報は以下を参照:\n"
"%(url)s\n"

#: ../do-release-upgrade:155
msgid "In /etc/update-manager/release-upgrades Prompt "
msgstr ""

#: ../do-release-upgrade:156
msgid "is set to never so upgrading is not possible."
msgstr ""

#: ../do-release-upgrade:158
msgid "There is no development version of an LTS available."
msgstr "入手可能なLTSの開発版はありません。"

#: ../do-release-upgrade:159
msgid "To upgrade to the latest non-LTS development release "
msgstr ""

#: ../do-release-upgrade:160
msgid "set Prompt=normal in /etc/update-manager/release-upgrades."
msgstr ""

#: ../do-release-upgrade:162
msgid "Upgrades to the development release are only "
msgstr "アップグレードできる開発版のリリースはこれだけです: "

#: ../do-release-upgrade:163
msgid "available from the latest supported release."
msgstr "最新のサポートされているリリースから入手できます。"

#: ../do-release-upgrade:165
msgid "No new release found."
msgstr "新しいリリースはありません。"

#: ../do-release-upgrade:170
msgid "Release upgrade not possible right now"
msgstr "今はリリースアップグレードができません。"

#: ../do-release-upgrade:171
#, c-format
msgid ""
"The release upgrade can not be performed currently, please try again later. "
"The server reported: '%s'"
msgstr ""
"リリースアップグレードが現在実行できないので後でもう一度試してください。サー"
"バーの報告は以下のとおりです: '%s'"

#: ../do-release-upgrade:177
#, c-format
msgid "New release '%s' available."
msgstr "新しいリリース '%s' が利用可能になっています。"

#: ../do-release-upgrade:178
msgid "Run 'do-release-upgrade' to upgrade to it."
msgstr "'do-release-upgrade' を実行してアップグレードしてください"

#: ../do-release-upgrade:195
msgid "Please install all available updates for your release before upgrading."
msgstr ""

#: ../do-release-upgrade:211
msgid ""
"You have not rebooted after updating a package which requires a reboot. "
"Please reboot before upgrading."
msgstr ""

#: ../check_new_release_gtk.py:86
msgid "Software Updater"
msgstr "ソフトウェアアップデーター"

#: ../check_new_release_gtk.py:118
#, python-format
msgid "Ubuntu %(version)s Upgrade Available"
msgstr "Ubuntu %(version)s のアップグレードが利用可能です"

#. print("don't upgrade")
#: ../check_new_release_gtk.py:149
#, python-format
msgid "You have declined the upgrade to Ubuntu %s"
msgstr "Ubuntu %s へのアップグレードを拒絶"

#: ../check_new_release_gtk.py:182
msgid "Check if upgrading to the latest devel release is possible"
msgstr "最新の開発リリースへのアップデートが利用可能かどうかチェックする"

#: ../check_new_release_gtk.py:191
msgid "Add debug output"
msgstr "デバッグ出力を追加"

#, fuzzy
#~ msgid "An upgrade is not possible at this time"
#~ msgstr "今はリリースアップグレードができません。"

#~ msgid "Could not calculate sources.list entry"
#~ msgstr "sources.listのエントリーから作業内容を見積もれません"

#~ msgid ""
#~ "Unable to locate any package files, perhaps this is not a Ubuntu Disc or "
#~ "the wrong architecture?"
#~ msgstr ""
#~ "パッケージファイルが見つかりません。UbuntuのCDではないか、異なるアーキテク"
#~ "チャー向けのCDかもしれません。"

#~ msgid "Failed to add the CD"
#~ msgstr "CDの追加に失敗しました"

#~ msgid ""
#~ "There was a error adding the CD, the upgrade will abort. Please report "
#~ "this as a bug if this is a valid Ubuntu CD.\n"
#~ "\n"
#~ "The error message was:\n"
#~ "'%s'"
#~ msgstr ""
#~ "CD をリソースとして追加できなかったため、アップグレードは終了されます。こ"
#~ "の CD が正規の Ubuntu CD の場合は、このことをバグとして報告してくださ"
#~ "い。\n"
#~ "\n"
#~ "エラーメッセージ：\n"
#~ "'%s'"

#~ msgid "Include latest updates from the Internet?"
#~ msgstr "インターネットからの最新のアップデート情報を取得しますか？"

#~ msgid ""
#~ "The upgrade system can use the internet to automatically download the "
#~ "latest updates and install them during the upgrade.  If you have a "
#~ "network connection this is highly recommended.\n"
#~ "\n"
#~ "The upgrade will take longer, but when it is complete, your system will "
#~ "be fully up to date.  You can choose not to do this, but you should "
#~ "install the latest updates soon after upgrading.\n"
#~ "If you answer 'no' here, the network is not used at all."
#~ msgstr ""
#~ "アップグレードシステムは、ネットワークを利用したシステムのアップグレードに"
#~ "対応しています。最新のパッケージを自動的にダウンロードし、アップグレード時"
#~ "に併せてインストールできるため、ネットワークへの接続が可能なら、この方法を"
#~ "使うことを強く推奨します。\n"
#~ "\n"
#~ "アップグレードには時間がかかりますが、ネットワークを利用すれば、完了時に最"
#~ "新のアップデータが導入された状態になります。ネットワークを利用しないアップ"
#~ "グレードも可能ですが、この場合はアップグレードが完了した後で、さらにアップ"
#~ "データをインストールする必要があります。\n"
#~ "ここで「いいえ」を選択すると、アップグレードにネットワークを利用しません。"

#~ msgid "Failed to add the cdrom"
#~ msgstr "cdromの追加に失敗しました"

#~ msgid "Sorry, adding the cdrom was not successful."
#~ msgstr "cdrom の追加に失敗しました。"

#~ msgid "Use the given path to search for a cdrom with upgradable packages"
#~ msgstr "アップグレードパッケージが含まれたCD-ROMへのパスを指定してください"

#~ msgid ""
#~ "An unresolvable problem occurred while calculating the upgrade:\n"
#~ "%s\n"
#~ "\n"
#~ " This can be caused by:\n"
#~ " * Upgrading to a pre-release version of Ubuntu\n"
#~ " * Running the current pre-release version of Ubuntu\n"
#~ " * Unofficial software packages not provided by Ubuntu\n"
#~ "\n"
#~ msgstr ""
#~ "アップグレードの見積もり中に解決できない問題が発生しました:\n"
#~ "%s\n"
#~ "\n"
#~ " 以下の原因が考えられます:\n"
#~ " * Ubuntu のリリース前バージョンへアップグレードしようとしている。\n"
#~ " * Ubuntu のリリース前バージョンを使っている。\n"
#~ " * Ubuntu が提供していない、非公式なパッケージを利用している。\n"
#~ "\n"

#~ msgid ""
#~ "Your system does not contain a ubuntu-desktop, kubuntu-desktop, xubuntu-"
#~ "desktop or edubuntu-desktop package and it was not possible to detect "
#~ "which version of Ubuntu you are running.\n"
#~ " Please install one of the packages above first using synaptic or apt-get "
#~ "before proceeding."
#~ msgstr ""
#~ "システムに ubuntu-desktop, kubuntu-desktop, xubuntu-desktop, もしくは"
#~ "edubuntu-desktop パッケージが含まれていません。このため、実行している "
#~ "ubuntu のバージョンが検出できません。 \n"
#~ " 続ける前に、Synaptic や apt-get を使用して、まずは上記のパッケージのうち"
#~ "のいずれかをインストールしてください。"

#~ msgid "Sandbox setup failed"
#~ msgstr "サンドボックス環境のセットアップに失敗しました"

#~ msgid "It was not possible to create the sandbox environment."
#~ msgstr "サンドボックス環境を構築することができませんでした。"

#~ msgid "Sandbox mode"
#~ msgstr "サンドボックスモード"

#~ msgid ""
#~ "This upgrade is running in sandbox (test) mode. All changes are written "
#~ "to '%s' and will be lost on the next reboot.\n"
#~ "\n"
#~ "*No* changes written to a system directory from now until the next reboot "
#~ "are permanent."
#~ msgstr ""
#~ "このアップグレードはサンドボックス(テスト)モードで実行中です。すべての変更"
#~ "は '%s' に書きこまれ、次に再起動したときに破棄されます。\n"
#~ "\n"
#~ "現時点から次に再起動するまでの間にシステムディレクトリに書き込まれた変更"
#~ "は、破棄されます。"

#~ msgid ""
#~ "Your python install is corrupted. Please fix the '/usr/bin/python' "
#~ "symlink."
#~ msgstr ""
#~ "インストールされたPythonが破損しています。シンボリックリンク'/usr/bin/"
#~ "python'を修正してください。"

#~ msgid "Package 'debsig-verify' is installed"
#~ msgstr "'debsig-verify'パッケージがインストールされています"

#~ msgid ""
#~ "The upgrade can not continue with that package installed.\n"
#~ "Please remove it with synaptic or 'apt-get remove debsig-verify' first "
#~ "and run the upgrade again."
#~ msgstr ""
#~ "'debsig-verify'パッケージがインストールされていると、アップグレードを継続"
#~ "することができません。\n"
#~ "Synapticパッケージマネージャーか 'apt-get remove debsig-verify' で削除した"
#~ "後で、再度アップグレードを実行してください。"

#~ msgid ""
#~ "While scanning your repository information no mirror entry for the "
#~ "upgrade was found. This can happen if you run a internal mirror or if the "
#~ "mirror information is out of date.\n"
#~ "\n"
#~ "Do you want to rewrite your 'sources.list' file anyway? If you choose "
#~ "'Yes' here it will update all '%s' to '%s' entries.\n"
#~ "If you select 'No' the upgrade will cancel."
#~ msgstr ""
#~ "システムに設定されたリポジトリ情報を確認しましたが、アップグレードに利用可"
#~ "能なミラーサーバーのエントリが見つかりませんでした。プライベートなミラー"
#~ "サーバーを利用していたり、ミラー情報が古い可能性があります。\n"
#~ "\n"
#~ "ミラーサーバーの設定ファイル 'sources.list' をとにかく編集しますか？　「は"
#~ "い」を選択すると、'%s' エントリは '%s' に置き換わります。\n"
#~ "「いいえ」を選択すると、アップグレードをキャンセルします。"

#~ msgid ""
#~ "The upgrade has aborted. The upgrade needs a total of %s free space on "
#~ "disk '%s'. Please free at least an additional %s of disk space on '%s'. "
#~ "Empty your trash and remove temporary packages of former installations "
#~ "using 'sudo apt-get clean'."
#~ msgstr ""
#~ "アップグレードを中断しました。アップグレードを行うには、 %s の空き容量が"
#~ "ディスク %s に必要です。少なくともあと %s の空き容量をディスク %s に作って"
#~ "ください。ゴミ箱を空にしたり、'sudo apt-get clean' を実行して今までにイン"
#~ "ストールした一時パッケージを削除してください。"

#~ msgid "evms in use"
#~ msgstr "evms は使用中です"

#~ msgid ""
#~ "Your system uses the 'evms' volume manager in /proc/mounts. The 'evms' "
#~ "software is no longer supported, please switch it off and run the upgrade "
#~ "again when this is done."
#~ msgstr ""
#~ "システムは/proc/mountsでボリュームマネジャとして 'evms' を使っていま"
#~ "す。'evms' ソフトウェアはもうサポートされていません。オフにしてからアップ"
#~ "グレードしてください。"

#~ msgid ""
#~ "This computer is currently using the NVIDIA 'nvidia' graphics driver. No "
#~ "version of this driver is available that works with your video card in "
#~ "Ubuntu 10.04 LTS.\n"
#~ "\n"
#~ "Do you want to continue?"
#~ msgstr ""
#~ "現在、このコンピューターはNVIDIA 'nvidia' グラフィックドライバーを利用して"
#~ "います。Ubuntu 10.04 LTS では、このハードウェアで動作可能なドライバーの"
#~ "バージョンはありません。\n"
#~ "\n"
#~ "作業を続けますか？"

#~ msgid "No i686 CPU"
#~ msgstr "i686 CPU ではありません"

#~ msgid ""
#~ "Your system uses an i586 CPU or a CPU that does not have the 'cmov' "
#~ "extension. All packages were built with optimizations requiring i686 as "
#~ "the minimal architecture. It is not possible to upgrade your system to a "
#~ "new Ubuntu release with this hardware."
#~ msgstr ""
#~ "あなたのコンピューターは、i586 CPU または 'cmov' 拡張命令に対応していない "
#~ "CPU を使用しています。すべてのパッケージは、最低限のアーキテクチャとして "
#~ "i686 を必要とする最適化でビルドされています。このハードウェアでは、新しい"
#~ "バージョンの Ubuntu にアップグレードすることができません。"

#~ msgid "Sandbox upgrade using aufs"
#~ msgstr "aufsを使用したサンドボックスアップグレード"

#~ msgid "Test upgrade with a sandbox aufs overlay"
#~ msgstr "aufsオーバレイを実験環境に用いてのテストアップグレード"

#~ msgid "No new release found"
#~ msgstr "新しくリリースされたものはありません"

#~ msgid ""
#~ "If none of this applies, then please report this bug using the command "
#~ "'ubuntu-bug ubuntu-release-upgrader-core' in a terminal."
#~ msgstr ""
#~ "いずれかにも当てはまらない場合には、端末上から 'ubuntu-bug ubuntu-release-"
#~ "upgrader-core' を実行してこのバグを報告してください。"

#~ msgid "Authentication is required to perform a partial upgrade"
#~ msgstr "部分アップグレードを行うのに認証が必要です"

#~ msgid "Authentication is required to perform a release upgrade"
#~ msgstr "リリースアップグレードを行うのに認証が必要です"

#~ msgid ""
#~ "An unresolvable problem occurred while calculating the upgrade.\n"
#~ "\n"
#~ " This can be caused by:\n"
#~ " * Upgrading to a pre-release version of Ubuntu\n"
#~ " * Running the current pre-release version of Ubuntu\n"
#~ " * Unofficial software packages not provided by Ubuntu\n"
#~ "\n"
#~ msgstr ""
#~ "アップグレードの計算中に修復不可能な問題が発生しました。\n"
#~ "\n"
#~ " 以下のことが原因の可能性があります:\n"
#~ " * リリース前のバージョンのUbuntuにアップグレードしている\n"
#~ " * リリース前のバージョンのUbuntuを実行している\n"
#~ " * Ubuntu以外から提供されている非公式パッケージ\n"
#~ "\n"

#~ msgid "<b><big>Upgrading Ubuntu to version 15.04</big></b>"
#~ msgstr "<b><big>Ubuntuをバージョン15.04にアップグレードしています</big></b>"

#~ msgid "<b><big>Upgrading Ubuntu to version 15.10</big></b>"
#~ msgstr "<b><big>Ubuntuをバージョン15.10にアップグレードしています</big></b>"

#~ msgid "apt architecture is i386"
#~ msgstr "aptアーキテクチャーがi386です"
